CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE public.colleges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  location text NOT NULL,
  fees integer NOT NULL,
  rating numeric(2,1) NOT NULL,
  courses text[] NOT NULL DEFAULT '{}',
  placements jsonb NOT NULL DEFAULT '{}'::jsonb,
  overview text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX colleges_location_idx ON public.colleges (location);
CREATE INDEX colleges_fees_idx ON public.colleges (fees);
CREATE INDEX colleges_name_trgm_idx ON public.colleges USING gin (name gin_trgm_ops);

ALTER TABLE public.colleges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Colleges are viewable by everyone"
  ON public.colleges FOR SELECT USING (true);

CREATE TABLE public.saved_colleges (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  college_id uuid NOT NULL REFERENCES public.colleges(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, college_id)
);

CREATE INDEX saved_colleges_user_idx ON public.saved_colleges (user_id);

ALTER TABLE public.saved_colleges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own saved"
  ON public.saved_colleges FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own saved"
  ON public.saved_colleges FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own saved"
  ON public.saved_colleges FOR DELETE USING (auth.uid() = user_id);

INSERT INTO public.colleges (name, location, fees, rating, courses, placements, overview) VALUES
('Indian Institute of Technology', 'Mumbai, MH', 80000, 3.2, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":60,"avg_package_lpa":4,"highest_package_lpa":20,"top_recruiters":["Google","Microsoft","Amazon","Goldman Sachs","McKinsey"]}'::jsonb, 'Indian Institute of Technology is a premier institution in Mumbai, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('National Institute of Sciences', 'Delhi, DL', 127000, 4.5, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":67,"avg_package_lpa":7,"highest_package_lpa":31,"top_recruiters":["Microsoft","Amazon","Goldman Sachs","McKinsey","Deloitte"]}'::jsonb, 'National Institute of Sciences is a premier institution in Delhi, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Royal Academy of Design', 'Bangalore, KA', 174000, 4, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":74,"avg_package_lpa":10,"highest_package_lpa":42,"top_recruiters":["Amazon","Goldman Sachs","McKinsey","Deloitte","TCS"]}'::jsonb, 'Royal Academy of Design is a premier institution in Bangalore, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('St. Xavier''s Business', 'Chennai, TN', 221000, 3.5, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":81,"avg_package_lpa":13,"highest_package_lpa":53,"top_recruiters":["Goldman Sachs","McKinsey","Deloitte","TCS","Infosys"]}'::jsonb, 'St. Xavier''s Business is a premier institution in Chennai, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Symbiosis Engineering', 'Kolkata, WB', 268000, 4.8, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":88,"avg_package_lpa":16,"highest_package_lpa":64,"top_recruiters":["McKinsey","Deloitte","TCS","Infosys","Wipro"]}'::jsonb, 'Symbiosis Engineering is a premier institution in Kolkata, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Amity Commerce', 'Pune, MH', 315000, 4.3, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":95,"avg_package_lpa":19,"highest_package_lpa":75,"top_recruiters":["Deloitte","TCS","Infosys","Wipro","Accenture"]}'::jsonb, 'Amity Commerce is a premier institution in Pune, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Manipal Liberal Arts', 'Hyderabad, TG', 362000, 3.8, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":62,"avg_package_lpa":22,"highest_package_lpa":86,"top_recruiters":["TCS","Infosys","Wipro","Accenture","JP Morgan"]}'::jsonb, 'Manipal Liberal Arts is a premier institution in Hyderabad, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Christ Management', 'Ahmedabad, GJ', 409000, 3.3, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":69,"avg_package_lpa":25,"highest_package_lpa":97,"top_recruiters":["Infosys","Wipro","Accenture","JP Morgan","Adobe"]}'::jsonb, 'Christ Management is a premier institution in Ahmedabad, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Loyola Arts and Sciences', 'Jaipur, RJ', 456000, 4.6, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":76,"avg_package_lpa":28,"highest_package_lpa":28,"top_recruiters":["Wipro","Accenture","JP Morgan","Adobe","Flipkart"]}'::jsonb, 'Loyola Arts and Sciences is a premier institution in Jaipur, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Heritage Architecture', 'Kanpur, UP', 503000, 4.1, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":83,"avg_package_lpa":31,"highest_package_lpa":39,"top_recruiters":["Accenture","JP Morgan","Adobe","Flipkart","Swiggy"]}'::jsonb, 'Heritage Architecture is a premier institution in Kanpur, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Apex Technology', 'Lucknow, UP', 550000, 3.6, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":90,"avg_package_lpa":34,"highest_package_lpa":50,"top_recruiters":["JP Morgan","Adobe","Flipkart","Swiggy","Razorpay"]}'::jsonb, 'Apex Technology is a premier institution in Lucknow, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Crescent Sciences', 'Indore, MP', 597000, 4.9, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":97,"avg_package_lpa":37,"highest_package_lpa":61,"top_recruiters":["Adobe","Flipkart","Swiggy","Razorpay","Google"]}'::jsonb, 'Crescent Sciences is a premier institution in Indore, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Greenfield Design', 'Bhopal, MP', 644000, 4.4, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":64,"avg_package_lpa":5,"highest_package_lpa":72,"top_recruiters":["Flipkart","Swiggy","Razorpay","Google","Microsoft"]}'::jsonb, 'Greenfield Design is a premier institution in Bhopal, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Northstar Business', 'Patna, BR', 691000, 3.9, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":71,"avg_package_lpa":8,"highest_package_lpa":83,"top_recruiters":["Swiggy","Razorpay","Google","Microsoft","Amazon"]}'::jsonb, 'Northstar Business is a premier institution in Patna, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Westwood Engineering', 'Chandigarh, CH', 738000, 3.4, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":78,"avg_package_lpa":11,"highest_package_lpa":94,"top_recruiters":["Razorpay","Google","Microsoft","Amazon","Goldman Sachs"]}'::jsonb, 'Westwood Engineering is a premier institution in Chandigarh, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Brookfield Commerce', 'Coimbatore, TN', 785000, 4.7, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":85,"avg_package_lpa":14,"highest_package_lpa":25,"top_recruiters":["Google","Microsoft","Amazon","Goldman Sachs","McKinsey"]}'::jsonb, 'Brookfield Commerce is a premier institution in Coimbatore, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Eastlake Liberal Arts', 'Kochi, KL', 832000, 4.2, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":92,"avg_package_lpa":17,"highest_package_lpa":36,"top_recruiters":["Microsoft","Amazon","Goldman Sachs","McKinsey","Deloitte"]}'::jsonb, 'Eastlake Liberal Arts is a premier institution in Kochi, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Summit Management', 'Nagpur, MH', 879000, 3.7, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":99,"avg_package_lpa":20,"highest_package_lpa":47,"top_recruiters":["Amazon","Goldman Sachs","McKinsey","Deloitte","TCS"]}'::jsonb, 'Summit Management is a premier institution in Nagpur, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Harborview Arts and Sciences', 'Surat, GJ', 926000, 3.2, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":66,"avg_package_lpa":23,"highest_package_lpa":58,"top_recruiters":["Goldman Sachs","McKinsey","Deloitte","TCS","Infosys"]}'::jsonb, 'Harborview Arts and Sciences is a premier institution in Surat, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Riverside Architecture', 'Vadodara, GJ', 973000, 4.5, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":73,"avg_package_lpa":26,"highest_package_lpa":69,"top_recruiters":["McKinsey","Deloitte","TCS","Infosys","Wipro"]}'::jsonb, 'Riverside Architecture is a premier institution in Vadodara, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Cedar Hill Technology', 'Mumbai, MH', 100000, 4, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":80,"avg_package_lpa":29,"highest_package_lpa":80,"top_recruiters":["Deloitte","TCS","Infosys","Wipro","Accenture"]}'::jsonb, 'Cedar Hill Technology is a premier institution in Mumbai, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Pinewood Sciences', 'Delhi, DL', 147000, 3.5, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":87,"avg_package_lpa":32,"highest_package_lpa":91,"top_recruiters":["TCS","Infosys","Wipro","Accenture","JP Morgan"]}'::jsonb, 'Pinewood Sciences is a premier institution in Delhi, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Stonebridge Design', 'Bangalore, KA', 194000, 4.8, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":94,"avg_package_lpa":35,"highest_package_lpa":22,"top_recruiters":["Infosys","Wipro","Accenture","JP Morgan","Adobe"]}'::jsonb, 'Stonebridge Design is a premier institution in Bangalore, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Lakeside Business', 'Chennai, TN', 241000, 4.3, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":61,"avg_package_lpa":38,"highest_package_lpa":33,"top_recruiters":["Wipro","Accenture","JP Morgan","Adobe","Flipkart"]}'::jsonb, 'Lakeside Business is a premier institution in Chennai, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Highland Engineering', 'Kolkata, WB', 288000, 3.8, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":68,"avg_package_lpa":6,"highest_package_lpa":44,"top_recruiters":["Accenture","JP Morgan","Adobe","Flipkart","Swiggy"]}'::jsonb, 'Highland Engineering is a premier institution in Kolkata, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Maplewood Commerce', 'Pune, MH', 335000, 3.3, ARRAY['B.Tech Computer Science','B.Tech Electronics','M.Tech AI','MBA','BBA']::text[], '{"placement_percentage":75,"avg_package_lpa":9,"highest_package_lpa":55,"top_recruiters":["JP Morgan","Adobe","Flipkart","Swiggy","Razorpay"]}'::jsonb, 'Maplewood Commerce is a premier institution in Pune, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Oakridge Liberal Arts', 'Hyderabad, TG', 382000, 4.6, ARRAY['B.Sc Physics','B.Sc Chemistry','M.Sc Math','B.A Economics','M.A English']::text[], '{"placement_percentage":82,"avg_package_lpa":12,"highest_package_lpa":66,"top_recruiters":["Adobe","Flipkart","Swiggy","Razorpay","Google"]}'::jsonb, 'Oakridge Liberal Arts is a premier institution in Hyderabad, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Ironwood Management', 'Ahmedabad, GJ', 429000, 4.1, ARRAY['B.Arch','B.Des','M.Des UX','BBA','B.Com']::text[], '{"placement_percentage":89,"avg_package_lpa":15,"highest_package_lpa":77,"top_recruiters":["Flipkart","Swiggy","Razorpay","Google","Microsoft"]}'::jsonb, 'Ironwood Management is a premier institution in Ahmedabad, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Silverline Arts and Sciences', 'Jaipur, RJ', 476000, 3.6, ARRAY['MBBS','BDS','B.Pharm','M.Sc Nursing','BPT']::text[], '{"placement_percentage":96,"avg_package_lpa":18,"highest_package_lpa":88,"top_recruiters":["Swiggy","Razorpay","Google","Microsoft","Amazon"]}'::jsonb, 'Silverline Arts and Sciences is a premier institution in Jaipur, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.'),
('Goldfield Architecture', 'Kanpur, UP', 523000, 4.9, ARRAY['LLB','LLM','BBA-LLB','B.A Political Science','M.A Sociology']::text[], '{"placement_percentage":63,"avg_package_lpa":21,"highest_package_lpa":99,"top_recruiters":["Razorpay","Google","Microsoft","Amazon","Goldman Sachs"]}'::jsonb, 'Goldfield Architecture is a premier institution in Kanpur, recognized for academic excellence, modern facilities, and an active campus life. Established with a vision to nurture future leaders, the college offers diverse programs across disciplines.');